### ISSUE TITLE
marker_offset offsets even when set to 0

### ISSUE THREAD

**Issue by sethaxen** [JuliaPlots/AbstractPlotting.jl#352]
Passing a `marker_offset` filled with `Point2f0(0, 0)` to `scatter` surprisingly still offsets the points by half of a dot radius. Is this the intended behavior?

```julia
julia> p = scatter(Point2f0.(0:10, 0:10); markersize=50px)
julia> scatter!(p, Point2f0.(0:10, 0:10); markersize=50px, marker_offset=fill(Point2f0(0, 0), 11), color=:orange)
```
![test](https://user-images.githubusercontent.com/8673634/76182482-476a1a00-6182-11ea-9fe8-98eb2f4d78de.png)

I also noticed that the offset seems to be in effective `px` units (as in, setting a marker size of `n px` and an offset of `n` shifts the dot by one dot diameter, which is going to be _really_ convenient for https://github.com/JuliaPlots/StatsMakie.jl/pull/107). It would be handy if this was documented somewhere.

**Comment by SimonDanisch** [comment]
So the problem here is, that marker_offset is by default markersize/2, to center the markers ;) 
It's in marker units to actually support offseting the marker before rotating it - which is kinda hard otherwise... The thinking is, that it's very easy to offset the marker in data space, by just adding to the coordinates
